-- Issue #10 baseline schema and RLS migration.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null,
  title text not null,
  release_date date,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint movies_tmdb_id_key unique (tmdb_id)
);

comment on table public.movies is
  'Cached TMDb movie metadata shared across users. Mutations are expected to come from trusted server-side jobs only.';
comment on column public.movies.release_date is
  'Cached theatrical release date used for fast calendar feed generation.';
comment on column public.movies.raw_json is
  'Full TMDb payload cache for future mapping without another external lookup.';

create table if not exists public.watchlist_items (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  movie_id bigint not null references public.movies (id) on delete cascade,
  added_at timestamptz not null default timezone('utc', now()),
  constraint watchlist_items_user_id_movie_id_key unique (user_id, movie_id)
);

comment on table public.watchlist_items is
  'Per-user saved movies. RLS must be the enforcement boundary for ownership, not client-side filtering.';

create table if not exists public.calendar_tokens (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  token text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint calendar_tokens_user_id_key unique (user_id),
  constraint calendar_tokens_token_key unique (token),
  constraint calendar_tokens_token_length_check check (char_length(token) >= 32)
);

comment on table public.calendar_tokens is
  'Bearer-style calendar feed credentials. Only the owning user should manage rows directly; feed lookup by token should use trusted server access.';
comment on column public.calendar_tokens.token is
  'Secret calendar subscription token. Store and compare server-side without exposing full values in logs or public UIs.';

create index if not exists movies_tmdb_id_idx on public.movies (tmdb_id);
create index if not exists watchlist_items_user_id_idx on public.watchlist_items (user_id);
create index if not exists watchlist_items_movie_id_idx on public.watchlist_items (movie_id);

alter table public.movies enable row level security;
alter table public.watchlist_items enable row level security;
alter table public.calendar_tokens enable row level security;

-- Policy intent:
-- - movies contains shared cache data, so authenticated users may read it but only trusted server-side code should mutate it.
-- - watchlist_items and calendar_tokens are user-owned tables and must never leak across accounts.
-- - the public calendar feed should resolve tokens through server-side access, not through a broad client-readable policy.
create policy "authenticated users can read cached movies"
  on public.movies
  for select
  to authenticated
  using (true);

create policy "users can view their own watchlist items"
  on public.watchlist_items
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert their own watchlist items"
  on public.watchlist_items
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can update their own watchlist items"
  on public.watchlist_items
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete their own watchlist items"
  on public.watchlist_items
  for delete
  to authenticated
  using (auth.uid() = user_id);

create policy "users can view their own calendar tokens"
  on public.calendar_tokens
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert their own calendar tokens"
  on public.calendar_tokens
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can update their own calendar tokens"
  on public.calendar_tokens
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete their own calendar tokens"
  on public.calendar_tokens
  for delete
  to authenticated
  using (auth.uid() = user_id);
